package main

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"crypto"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha1"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// LinuxPkg is what a package for Alpine or Void depends on, by the
// system's names, comma separated. The system is packaged for when its
// section is there.
type LinuxPkg struct {
	Depends string `toml:"depends"`
	// Arches narrows the architectures packaged, or adds others, such as
	// RISC-V or 32-bit Intel; x86-64 and ARM64 when it's empty.
	Arches []string `toml:"arches"`
}

// alpineVersion is a version as apk allows it: numbers, and a suffix
// such as _beta2 for one before a release. "1.2.3-beta" becomes
// "1.2.3_beta".
func alpineVersion(v string) (string, error) {
	m := regexp.MustCompile(`^(\d+(?:\.\d+)*[a-z]?)(?:[-~_.]?(alpha|beta|pre|rc)\.?(\d*))?$`).FindStringSubmatch(v)
	if m == nil {
		return "", fmt.Errorf("version %s isn't one apk can hold: numbers, then alpha, beta, pre or rc", v)
	}
	if m[2] != "" {
		return m[1] + "_" + m[2] + m[3], nil
	}
	return m[1], nil
}

// alpinePackage is NAME-VERSION-r0-ARCH.apk, as packageAlpine names
// them, unsigned until vero-repo build signs them.
func alpinePackage(name string) *regexp.Regexp {
	return regexp.MustCompile(`^` + regexp.QuoteMeta(name) + `-([^-]+-r0)-(` + linuxArchNames("alpine") + `)\.apk$`)
}

// alpineDepends is what an Alpine package depends on: [gtk.alpine]'s, or
// GTK 4 for Python.
func alpineDepends(a *App) []string {
	if d := splitList(a.GTK.Alpine.Depends); len(d) > 0 {
		return d
	}
	return []string{"python3", "py3-gobject3", "gtk4.0"}
}

// packageAlpine builds the app's Alpine package for each architecture,
// in Go, as abuild would but for the signature, which vero-repo build
// adds: two gzip streams, one after the other - the control segment,
// .PKGINFO, then the files, each with its SHA-1 in the tar, as apk checks
// them.
func packageAlpine(a *App, workers map[string]string, out string) error {
	version, err := alpineVersion(a.Version)
	if err != nil {
		return err
	}
	for _, arch := range a.linuxArches("alpine") {
		files, err := linuxTree(a, "/usr", workers[arch.goarch], a.Name)
		if err != nil {
			return err
		}
		data, err := alpineData(files)
		if err != nil {
			return err
		}
		var size int64
		for _, f := range files {
			size += int64(len(f.data))
		}
		sum := sha256.Sum256(data)
		var info strings.Builder
		info.WriteString("# Generated by vero-repo\n")
		fmt.Fprintf(&info, "pkgname = %s\npkgver = %s-r0\npkgdesc = %s\n", a.Name, version, a.Summary)
		if a.Homepage != "" {
			fmt.Fprintf(&info, "url = %s\n", a.Homepage)
		}
		licence := a.Licence
		if licence == "" {
			licence = "custom"
		}
		fmt.Fprintf(&info, "builddate = %d\npackager = %s\nsize = %d\narch = %s\norigin = %s\nmaintainer = %s\nlicense = %s\n",
			buildTime().Unix(), a.Publisher, size, arch.name, a.Name, a.Publisher, licence)
		for _, d := range alpineDepends(a) {
			fmt.Fprintf(&info, "depend = %s\n", d)
		}
		fmt.Fprintf(&info, "datahash = %s\n", hex.EncodeToString(sum[:]))
		control, err := tarSegment([]treeFile{{".PKGINFO", []byte(info.String()), 0o644}})
		if err != nil {
			return err
		}
		name := filepath.Join(out, fmt.Sprintf("%s-%s-r0-%s.apk", a.Name, version, arch.name))
		if err := os.MkdirAll(out, 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(name, append(control, data...), 0o644); err != nil {
			return err
		}
		fmt.Println("built", name)
	}
	return nil
}

// tarSegment is files as a tar without its ending, gzipped: apk's
// signature and control segments, which run on into what follows.
func tarSegment(files []treeFile) ([]byte, error) {
	var b bytes.Buffer
	z := gzip.NewWriter(&b)
	tw := tar.NewWriter(z)
	for _, f := range files {
		if err := tw.WriteHeader(&tar.Header{
			Typeflag: tar.TypeReg, Name: f.path, Mode: int64(f.mode.Perm()), Size: int64(len(f.data)), ModTime: buildTime(),
			Uname: "root", Gname: "root", Format: tar.FormatUSTAR,
		}); err != nil {
			return nil, err
		}
		if _, err := tw.Write(f.data); err != nil {
			return nil, err
		}
	}
	// Flush pads the last file, but writes no ending, as Close would.
	if err := tw.Flush(); err != nil {
		return nil, err
	}
	if err := z.Close(); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// alpineData is a package's files, as a whole tar, gzipped, each file
// with its SHA-1, as abuild-tar --hash records it.
func alpineData(files []treeFile) ([]byte, error) {
	var b bytes.Buffer
	z := gzip.NewWriter(&b)
	tw := tar.NewWriter(z)
	mtime := buildTime()
	for _, e := range treeEntries(files) {
		h := &tar.Header{Name: strings.TrimPrefix(e.path, "/"), ModTime: mtime, Uname: "root", Gname: "root", Format: tar.FormatPAX}
		if e.dir {
			h.Typeflag, h.Name, h.Mode = tar.TypeDir, h.Name+"/", 0o755
		} else {
			sum := sha1.Sum(e.data)
			h.Typeflag, h.Mode, h.Size = tar.TypeReg, int64(e.mode.Perm()), int64(len(e.data))
			h.PAXRecords = map[string]string{"APK-TOOLS.checksum.SHA1": hex.EncodeToString(sum[:])}
		}
		if err := tw.WriteHeader(h); err != nil {
			return nil, err
		}
		if _, err := tw.Write(e.data); err != nil {
			return nil, err
		}
	}
	if err := tw.Close(); err != nil {
		return nil, err
	}
	if err := z.Close(); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// gzipStreams splits data into the gzip streams it's made of, as apk
// reads a package or an index: each is checked or hashed on its own.
func gzipStreams(data []byte) ([][]byte, error) {
	var out [][]byte
	for len(data) > 0 {
		r := bytes.NewReader(data)
		z, err := gzip.NewReader(r)
		if err != nil {
			return nil, err
		}
		z.Multistream(false)
		if _, err := io.Copy(io.Discard, z); err != nil {
			return nil, err
		}
		used := len(data) - r.Len()
		out = append(out, data[:used])
		data = data[used:]
	}
	return out, nil
}

// gunzipTar is the files in one gzipped tar, or tar segment, by name.
func gunzipTar(stream []byte) (map[string][]byte, *tar.Header, error) {
	z, err := gzip.NewReader(bytes.NewReader(stream))
	if err != nil {
		return nil, nil, err
	}
	z.Multistream(false)
	tr := tar.NewReader(z)
	out := map[string][]byte{}
	var first *tar.Header
	for {
		h, err := tr.Next()
		if err == io.EOF || err == io.ErrUnexpectedEOF && first != nil {
			return out, first, nil
		}
		if err != nil {
			return nil, nil, err
		}
		if first == nil {
			first = h
		}
		out[h.Name], _ = io.ReadAll(tr)
	}
}

// alpineKeyName is the name of the key's file in /etc/apk/keys, which
// a signature names.
func alpineKeyName(a *App) string { return a.Name + ".rsa.pub" }

// alpineSign signs stream as apk checks it, with RSA and SHA-256, and is
// the signature segment that goes before it.
func alpineSign(a *App, stream []byte, s *signer) ([]byte, error) {
	k, err := s.rsaKey()
	if err != nil {
		return nil, err
	}
	sum := sha256.Sum256(stream)
	sig, err := rsa.SignPKCS1v15(rand.Reader, k, crypto.SHA256, sum[:])
	if err != nil {
		return nil, err
	}
	return tarSegment([]treeFile{{".SIGN.RSA256." + alpineKeyName(a), sig, 0o644}})
}

// apkInfo is an Alpine package's .PKGINFO, as fields in order, and its
// control segment.
func apkInfo(pkg []byte) ([][2]string, []byte, error) {
	streams, err := gzipStreams(pkg)
	if err != nil {
		return nil, nil, err
	}
	for _, st := range streams {
		files, _, err := gunzipTar(st)
		if err != nil {
			return nil, nil, err
		}
		if body, ok := files[".PKGINFO"]; ok {
			var info [][2]string
			for _, line := range strings.Split(string(body), "\n") {
				if k, v, ok := strings.Cut(line, " = "); ok && !strings.HasPrefix(line, "#") {
					info = append(info, [2]string{k, v})
				}
			}
			return info, st, nil
		}
	}
	return nil, nil, errors.New("no .PKGINFO")
}

// buildAlpine makes site/alpine/ARCH a repository apk installs and
// updates from, for each architecture: the newest keep packages, each
// signed, and APKINDEX.tar.gz, the index, signed too, as abuild-sign signs
// them. key.rsa.pub beside them is the public key apk checks them with.
// It returns the newest package of each architecture.
func buildAlpine(site string, newPkgs []string, keep int, a *App, s *signer) (map[string]Download, error) {
	newest := map[string]Download{}
	match := alpinePackage(a.Name)
	inRepo := regexp.MustCompile(`^` + regexp.QuoteMeta(a.Name) + `-([^-]+)-r0\.apk$`)
	for _, arch := range a.linuxArches("alpine") {
		dir := filepath.Join(site, "alpine", arch.name)
		for _, p := range newPkgs {
			m := match.FindStringSubmatch(filepath.Base(p))
			if m == nil || m[2] != arch.name {
				continue
			}
			data, err := os.ReadFile(p)
			if err != nil {
				return nil, err
			}
			streams, err := gzipStreams(data)
			if err != nil || len(streams) != 2 {
				return nil, fmt.Errorf("%s isn't a package vero-repo made: %v", p, err)
			}
			sig, err := alpineSign(a, streams[0], s)
			if err != nil {
				return nil, err
			}
			if err := os.MkdirAll(dir, 0o755); err != nil {
				return nil, err
			}
			if err := os.WriteFile(filepath.Join(dir, a.Name+"-"+m[1]+".apk"), append(sig, data...), 0o644); err != nil {
				return nil, err
			}
		}
		files, versions, err := keepNewest(dir, inRepo, keep)
		if err != nil {
			return nil, err
		}
		if len(files) == 0 {
			continue
		}
		var index strings.Builder
		for _, f := range files {
			data, err := os.ReadFile(filepath.Join(dir, f))
			if err != nil {
				return nil, err
			}
			info, control, err := apkInfo(data)
			if err != nil {
				return nil, fmt.Errorf("%s: %w", f, err)
			}
			index.WriteString(apkIndexEntry(info, control, len(data)))
		}
		var desc bytes.Buffer
		z := gzip.NewWriter(&desc)
		tw := tar.NewWriter(z)
		for _, f := range []treeFile{{"DESCRIPTION", []byte(a.DisplayName), 0o644}, {"APKINDEX", []byte(index.String()), 0o644}} {
			if err := tarFile(tw, f.path, f.data, f.mode, buildTime()); err != nil {
				return nil, err
			}
		}
		if err := tw.Close(); err != nil {
			return nil, err
		}
		if err := z.Close(); err != nil {
			return nil, err
		}
		sig, err := alpineSign(a, desc.Bytes(), s)
		if err != nil {
			return nil, err
		}
		if err := os.WriteFile(filepath.Join(dir, "APKINDEX.tar.gz"), append(sig, desc.Bytes()...), 0o644); err != nil {
			return nil, err
		}
		newest[arch.name] = Download{Version: versions[files[0]], URL: filepathRel(site, filepath.Join(dir, files[0]))}
	}
	if len(newest) == 0 {
		return nil, nil
	}
	key, err := s.rsaPublicPEM()
	if err != nil {
		return nil, err
	}
	return newest, os.WriteFile(filepath.Join(site, "alpine", alpineKeyName(a)), key, 0o644)
}

// apkIndexEntry is a package's entry in APKINDEX: C, the SHA-1 of its
// control segment, by which apk knows it, then what .PKGINFO says.
func apkIndexEntry(info [][2]string, control []byte, size int) string {
	sum := sha1.Sum(control)
	var b strings.Builder
	fmt.Fprintf(&b, "C:Q1%s\n", base64.StdEncoding.EncodeToString(sum[:]))
	for _, f := range []struct{ letter, key string }{
		{"P", "pkgname"}, {"V", "pkgver"}, {"A", "arch"}, {"S", ""}, {"I", "size"}, {"T", "pkgdesc"},
		{"U", "url"}, {"L", "license"}, {"o", "origin"}, {"m", "maintainer"}, {"t", "builddate"},
	} {
		v := pkgInfo(info, f.key)
		if f.letter == "S" {
			v = fmt.Sprint(size)
		}
		if v != "" {
			fmt.Fprintf(&b, "%s:%s\n", f.letter, v)
		}
	}
	if d := pkgInfoAll(info, "depend"); len(d) > 0 {
		fmt.Fprintf(&b, "D:%s\n", strings.Join(d, " "))
	}
	return b.String() + "\n"
}
