package main

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"crypto/md5"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/ProtonMail/go-crypto/openpgp"
	"github.com/klauspost/compress/zstd"
)

// pacmanVersion is a version as Arch's pkgver allows it, with no hyphen:
// "1.2.3-beta" becomes "1.2.3_beta", which pacman counts as before 1.2.3.
func pacmanVersion(v string) string {
	return strings.NewReplacer("-", "_", "~", "_").Replace(v)
}

// pacmanPackage is NAME-VERSION-1-ARCH.pkg.tar.zst, as packagePacman
// names them.
func pacmanPackage(name string) *regexp.Regexp {
	return regexp.MustCompile(`^` + regexp.QuoteMeta(name) + `-([^-]+)-1-(` + linuxArchNames("arch") + `)\.pkg\.tar\.zst$`)
}

// pacmanDepends is what an Arch package depends on: [gtk.arch]'s, or GTK
// 4 for Python.
func pacmanDepends(a *App) []string {
	if d := splitList(a.GTK.Arch.Depends); len(d) > 0 {
		return d
	}
	return []string{"python", "python-gobject", "gtk4"}
}

// packagePacman builds the app's Arch Linux package for each
// architecture, in Go, as makepkg would: the same files as the .deb,
// under /usr, in a tar compressed with zstd, which begins with .PKGINFO,
// saying what it is, and .MTREE, the hash of every file. vero-repo build
// signs it, and puts it in the site's pacman repository.
func packagePacman(a *App, workers map[string]string, out string) error {
	for _, arch := range a.linuxArches("arch") {
		files, err := linuxTree(a, "/usr", workers[arch.goarch], a.Name)
		if err != nil {
			return err
		}
		name := filepath.Join(out, fmt.Sprintf("%s-%s-1-%s.pkg.tar.zst", a.Name, pacmanVersion(a.Version), arch.name))
		if err := writePacman(name, pacmanInfo(a, arch.name, files), files); err != nil {
			return err
		}
		fmt.Println("built", name)
	}
	return nil
}

// pacmanInfo is a package's .PKGINFO.
func pacmanInfo(a *App, arch string, files []treeFile) []byte {
	var size int64
	for _, f := range files {
		size += int64(len(f.data))
	}
	licence := a.Licence
	if licence == "" {
		licence = "custom"
	}
	var b strings.Builder
	b.WriteString("# Generated by vero-repo\n")
	fmt.Fprintf(&b, "pkgname = %s\npkgbase = %s\nxdata = pkgtype=pkg\npkgver = %s-1\n", a.Name, a.Name, pacmanVersion(a.Version))
	fmt.Fprintf(&b, "pkgdesc = %s\n", a.Summary)
	if a.Homepage != "" {
		fmt.Fprintf(&b, "url = %s\n", a.Homepage)
	}
	fmt.Fprintf(&b, "builddate = %d\npackager = %s\nsize = %d\narch = %s\nlicense = %s\n", buildTime().Unix(), a.Publisher, size, arch, licence)
	for _, d := range pacmanDepends(a) {
		fmt.Fprintf(&b, "depend = %s\n", d)
	}
	for _, d := range splitList(a.GTK.Arch.OptDepends) {
		fmt.Fprintf(&b, "optdepend = %s\n", d)
	}
	return []byte(b.String())
}

// treeEntry is a file or folder of a package, in the order a package's
// tar has them: each folder before what's in it.
type treeEntry struct {
	treeFile
	dir bool
}

// treeEntries are files, with every folder they're in but /, sorted.
func treeEntries(files []treeFile) []treeEntry {
	var out []treeEntry
	dirs := map[string]bool{}
	sorted := append([]treeFile(nil), files...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].path < sorted[j].path })
	for _, f := range sorted {
		var parents []string
		for d := path.Dir(f.path); d != "/" && !dirs[d]; d = path.Dir(d) {
			parents = append(parents, d)
			dirs[d] = true
		}
		for i := len(parents) - 1; i >= 0; i-- {
			out = append(out, treeEntry{treeFile{path: parents[i], mode: 0o755}, true})
		}
		out = append(out, treeEntry{f, false})
	}
	return out
}

// writePacman writes an Arch package: .PKGINFO, .MTREE, then the files.
func writePacman(name string, info []byte, files []treeFile) error {
	mtime := buildTime()
	entries := treeEntries(files)
	var mtree bytes.Buffer
	stamp := fmt.Sprintf("%d.0", mtime.Unix())
	fmt.Fprintf(&mtree, "#mtree\n/set type=file uid=0 gid=0 mode=644\n")
	fmt.Fprintf(&mtree, "./.PKGINFO time=%s size=%d md5digest=%x sha256digest=%x\n", stamp, len(info), md5.Sum(info), sha256.Sum256(info))
	for _, e := range entries {
		if e.dir {
			fmt.Fprintf(&mtree, "./%s time=%s mode=755 type=dir\n", strings.TrimPrefix(e.path, "/"), stamp)
			continue
		}
		fmt.Fprintf(&mtree, "./%s time=%s mode=%o size=%d md5digest=%x sha256digest=%x\n",
			strings.TrimPrefix(e.path, "/"), stamp, e.mode.Perm(), len(e.data), md5.Sum(e.data), sha256.Sum256(e.data))
	}
	var gz bytes.Buffer
	zw := gzip.NewWriter(&gz)
	zw.Write(mtree.Bytes())
	zw.Close()

	var b bytes.Buffer
	z, err := zstd.NewWriter(&b)
	if err != nil {
		return err
	}
	tw := tar.NewWriter(z)
	if err := tarFile(tw, ".PKGINFO", info, 0o644, mtime); err != nil {
		return err
	}
	if err := tarFile(tw, ".MTREE", gz.Bytes(), 0o644, mtime); err != nil {
		return err
	}
	for _, e := range entries {
		rel := strings.TrimPrefix(e.path, "/")
		if e.dir {
			err = tarDir(tw, rel+"/", mtime)
		} else {
			err = tarFile(tw, rel, e.data, e.mode, mtime)
		}
		if err != nil {
			return err
		}
	}
	if err := tw.Close(); err != nil {
		return err
	}
	if err := z.Close(); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(name), 0o755); err != nil {
		return err
	}
	return os.WriteFile(name, b.Bytes(), 0o644)
}

// readPacman is a package's .PKGINFO, as fields in order, and the files
// and folders in it, as pacman lists them: folders end in a slash.
func readPacman(data []byte) ([][2]string, []string, error) {
	z, err := zstd.NewReader(bytes.NewReader(data))
	if err != nil {
		return nil, nil, err
	}
	defer z.Close()
	tr := tar.NewReader(z)
	var info [][2]string
	var files []string
	for {
		h, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, nil, err
		}
		switch {
		case h.Name == ".PKGINFO":
			body, err := io.ReadAll(tr)
			if err != nil {
				return nil, nil, err
			}
			for _, line := range strings.Split(string(body), "\n") {
				if k, v, ok := strings.Cut(line, " = "); ok && !strings.HasPrefix(line, "#") {
					info = append(info, [2]string{k, v})
				}
			}
		case strings.HasPrefix(h.Name, "."):
		default:
			files = append(files, h.Name)
		}
	}
	if info == nil {
		return nil, nil, errors.New("no .PKGINFO")
	}
	return info, files, nil
}

// pkgInfo is the first value of key in a .PKGINFO, and pkgInfoAll every
// one.
func pkgInfo(info [][2]string, key string) string {
	for _, kv := range info {
		if kv[0] == key {
			return kv[1]
		}
	}
	return ""
}

func pkgInfoAll(info [][2]string, key string) []string {
	var out []string
	for _, kv := range info {
		if kv[0] == key {
			out = append(out, kv[1])
		}
	}
	return out
}

// detachBinary is a signature of data, unarmored, as pacman reads a .sig.
func (s *signer) detachBinary(data []byte) ([]byte, error) {
	var out bytes.Buffer
	if err := openpgp.DetachSign(&out, s.entity, bytes.NewReader(data), signConfig); err != nil {
		return nil, err
	}
	return out.Bytes(), nil
}

// buildPacman makes site/arch/ARCH a repository pacman installs and
// updates from, as repo-add makes one, for each architecture: the newest
// keep packages, each with its signature beside it, and NAME.db and
// NAME.files, the indexes, signed too. The repository is named after the
// app, which is how pacman.conf names it. It returns the newest package
// of each architecture.
func buildPacman(site string, newPkgs []string, keep int, a *App, s *signer) (map[string]Download, error) {
	newest := map[string]Download{}
	match := pacmanPackage(a.Name)
	for _, arch := range a.linuxArches("arch") {
		dir := filepath.Join(site, "arch", arch.name)
		for _, p := range newPkgs {
			if m := match.FindStringSubmatch(filepath.Base(p)); m != nil && m[2] == arch.name {
				if err := copyFile(p, filepath.Join(dir, filepath.Base(p))); err != nil {
					return nil, err
				}
				os.Remove(filepath.Join(dir, filepath.Base(p)+".sig"))
			}
		}
		files, versions, err := keepNewest(dir, match, keep)
		if err != nil {
			return nil, err
		}
		if len(files) == 0 {
			continue
		}
		// Signatures of packages no longer kept go with them.
		sigs, _ := filepath.Glob(filepath.Join(dir, "*.pkg.tar.zst.sig"))
		for _, sig := range sigs {
			if _, err := os.Stat(strings.TrimSuffix(sig, ".sig")); err != nil {
				os.Remove(sig)
			}
		}
		// The indexes list one version of each package, the newest, as
		// pacman expects; the older stay beside it, signed, for anyone
		// who needs to go back.
		for _, f := range files[1:] {
			if _, err := os.Stat(filepath.Join(dir, f+".sig")); err != nil {
				data, err := os.ReadFile(filepath.Join(dir, f))
				if err != nil {
					return nil, err
				}
				sig, err := s.detachBinary(data)
				if err != nil {
					return nil, err
				}
				if err := os.WriteFile(filepath.Join(dir, f+".sig"), sig, 0o644); err != nil {
					return nil, err
				}
			}
		}
		db, filesDB, err := pacmanIndexes(dir, files[:1], s)
		if err != nil {
			return nil, err
		}
		for name, data := range map[string][]byte{".db": db, ".files": filesDB} {
			sig, err := s.detachBinary(data)
			if err != nil {
				return nil, err
			}
			// NAME.db is what pacman fetches; repo-add makes it a link to
			// NAME.db.tar.gz, which a web host may not serve, so here
			// it's a copy.
			for _, f := range []string{a.Name + name, a.Name + name + ".tar.gz"} {
				if err := os.WriteFile(filepath.Join(dir, f), data, 0o644); err != nil {
					return nil, err
				}
				if err := os.WriteFile(filepath.Join(dir, f+".sig"), sig, 0o644); err != nil {
					return nil, err
				}
			}
		}
		newest[arch.name] = Download{Version: versions[files[0]], URL: filepathRel(site, filepath.Join(dir, files[0]))}
	}
	return newest, nil
}

// pacmanIndexes are a repository's NAME.db and NAME.files, for the
// packages in dir, signing any package that has no signature yet: a
// tar, gzipped, with a folder for each package holding desc, and in
// NAME.files, files too.
func pacmanIndexes(dir string, pkgs []string, s *signer) ([]byte, []byte, error) {
	var db, filesDB bytes.Buffer
	dbz, fz := gzip.NewWriter(&db), gzip.NewWriter(&filesDB)
	dbt, ft := tar.NewWriter(dbz), tar.NewWriter(fz)
	mtime := buildTime()
	for _, p := range pkgs {
		data, err := os.ReadFile(filepath.Join(dir, p))
		if err != nil {
			return nil, nil, err
		}
		sig, err := os.ReadFile(filepath.Join(dir, p+".sig"))
		if err != nil {
			if sig, err = s.detachBinary(data); err != nil {
				return nil, nil, err
			}
			if err := os.WriteFile(filepath.Join(dir, p+".sig"), sig, 0o644); err != nil {
				return nil, nil, err
			}
		}
		info, files, err := readPacman(data)
		if err != nil {
			return nil, nil, fmt.Errorf("%s: %w", p, err)
		}
		desc := pacmanDesc(p, data, sig, info)
		folder := pkgInfo(info, "pkgname") + "-" + pkgInfo(info, "pkgver") + "/"
		var list strings.Builder
		list.WriteString("%FILES%\n")
		for _, f := range files {
			list.WriteString(f + "\n")
		}
		list.WriteString("\n")
		for _, tw := range []*tar.Writer{dbt, ft} {
			if err := tarDir(tw, folder, mtime); err != nil {
				return nil, nil, err
			}
			if err := tarFile(tw, folder+"desc", desc, 0o644, mtime); err != nil {
				return nil, nil, err
			}
		}
		if err := tarFile(ft, folder+"files", []byte(list.String()), 0o644, mtime); err != nil {
			return nil, nil, err
		}
	}
	for _, c := range []io.Closer{dbt, ft, dbz, fz} {
		if err := c.Close(); err != nil {
			return nil, nil, err
		}
	}
	return db.Bytes(), filesDB.Bytes(), nil
}

// pacmanDesc is a package's desc in a repository's index, as repo-add
// writes it: each field's name, its values a line each, then a blank
// line.
func pacmanDesc(file string, data, sig []byte, info [][2]string) []byte {
	var b strings.Builder
	field := func(name string, values ...string) {
		if len(values) == 0 || values[0] == "" {
			return
		}
		fmt.Fprintf(&b, "%%%s%%\n%s\n\n", name, strings.Join(values, "\n"))
	}
	field("FILENAME", file)
	field("NAME", pkgInfo(info, "pkgname"))
	field("BASE", pkgInfo(info, "pkgbase"))
	field("VERSION", pkgInfo(info, "pkgver"))
	field("DESC", pkgInfo(info, "pkgdesc"))
	field("CSIZE", fmt.Sprint(len(data)))
	field("ISIZE", pkgInfo(info, "size"))
	field("MD5SUM", fmt.Sprintf("%x", md5.Sum(data)))
	sum := sha256.Sum256(data)
	field("SHA256SUM", hex.EncodeToString(sum[:]))
	field("PGPSIG", base64.StdEncoding.EncodeToString(sig))
	field("URL", pkgInfo(info, "url"))
	field("LICENSE", pkgInfoAll(info, "license")...)
	field("ARCH", pkgInfo(info, "arch"))
	field("BUILDDATE", pkgInfo(info, "builddate"))
	field("PACKAGER", pkgInfo(info, "packager"))
	field("DEPENDS", pkgInfoAll(info, "depend")...)
	field("OPTDEPENDS", pkgInfoAll(info, "optdepend")...)
	return []byte(b.String())
}

// keyFingerprint is the signing key's fingerprint, as pacman-key takes it.
func (s *signer) keyFingerprint() string {
	return strings.ToUpper(hex.EncodeToString(s.entity.PrimaryKey.Fingerprint))
}
